### ISSUE TITLE
MTBench Branch evaluator breaks when it encounters av3 taxonomy qna.yaml

### ISSUE THREAD

**Issue by bcrochet** [instructlab/eval#87]
It currently is trying to parse files as v2 taxonomy yaml.

**Comment by bcrochet** [comment]
Results:

```
$ ilab model evaluate --benchmark mt_bench_branch --judge-model /home/bcrochet/.cache/instructlab/models/prometheus-8x7b-v2-0 --model /home/bcrochet/.local/share/instructlab/checkpoints/hf_format/samples_1920 --base-model /home/bcrochet/.cache/instructlab/models/granite-7b-lab --branch rc --base-branch main --merge-system-user-message --enable-serving-output 
Using local model found at '/home/bcrochet/.local/share/instructlab/checkpoints/hf_format/samples_1920' for '--model'
INFO 2024-08-01 09:15:17,279 numexpr.utils:145: Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO 2024-08-01 09:15:17,279 numexpr.utils:148: Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO 2024-08-01 09:15:17,279 numexpr.utils:161: NumExpr defaulting to 16 threads.
Generating questions and reference answers from qna files for branch rc...
WARNING 2024-08-01 09:15:17,454 instructlab.model.evaluate:301: Based on your hardware configuration, when using vLLM, we recommend setting max-workers between 85.0 and 256.0 for optimal performance
INFO 2024-08-01 09:15:17,819 instructlab.model.backends.backends:315: Trying to connect to model server at http://127.0.0.1:8000/v1
INFO 2024-08-01 09:15:20,437 instructlab.model.backends.vllm:197: vLLM starting up on pid 140669 at http://127.0.0.1:43281/v1
INFO 2024-08-01 09:15:20,437 instructlab.model.backends.backends:328: Starting a temporary vLLM server at http://127.0.0.1:43281/v1
INFO 2024-08-01 09:15:20,437 instructlab.model.backends.backends:336: Waiting for the vLLM server to start at http://127.0.0.1:43281/v1, this might take a moment... Attempt: 1/80
INFO 2024-08-01 09:15:25,371 instructlab.model.backends.backends:336: Waiting for the vLLM server to start at http://127.0.0.1:43281/v1, this might take a moment... Attempt: 2/80
INFO 2024-08-01 09:15:30,101 instructlab.model.backends.backends:336: Waiting for the vLLM server to start at http://127.0.0.1:43281/v1, this might take a moment... Attempt: 3/80
INFO 2024-08-01 09:15:34,487 instructlab.model.backends.backends:336: Waiting for the vLLM server to start at http://127.0.0.1:43281/v1, this might take a moment... Attempt: 4/80
INFO 2024-08-01 09:15:39,428 instructlab.model.backends.backends:336: Waiting for the vLLM server to start at http://127.0.0.1:43281/v1, this might take a moment... Attempt: 5/80
embedding_mode is False. Embedding API will not work.
INFO:     Started server process [140669]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:43281 (Press CTRL+C to quit)
INFO:     127.0.0.1:43734 - "GET /v1/models HTTP/1.1" 200 OK
INFO 2024-08-01 09:15:40,323 instructlab.model.backends.backends:343: vLLM engine successfully started at http://127.0.0.1:43281/v1
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 147/149 [00:00<00:00, 214.45it/s]
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [140669]
Traceback (most recent call last):
  File "/home/bcrochet/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/venv/lib64/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/instructlab/instructlab/src/instructlab/clickext.py", line 292, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bcrochet/instructlab/instructlab/src/instructlab/model/evaluate.py", line 614, in evaluate
    evaluator.gen_answers(api_base)
  File "/home/bcrochet/instructlab/eval/src/instructlab/eval/mt_bench.py", line 131, in gen_answers
    mt_bench_branch_generator.generate(
  File "/home/bcrochet/instructlab/eval/src/instructlab/eval/mt_bench_branch_generator.py", line 59, in generate
    q, a = ex["question"], ex["answer"]
           ~~^^^^^^^^^^^^
KeyError: 'question'
```

**Comment by bcrochet** [comment]
It appears that the issue in earlier testing was that the eval library was specifically looking for qna.yaml (as it should) and so anything NOT named that was not even part of the evaluation.

**Comment by bcrochet** [comment]
So, this shouldn't be reading knowledge at all. So the fix instead is to exclude the knowledge dir from the taxonomy branch.
